### ISSUE TITLE
YAML2Yeast Does Not Work Correctly (macOS, GHCI 8.2.2)

### ISSUE THREAD

**Issue by sanssecours** [orenbenkiki/yamlreference#1]
👋 Hi,

thank you for providing this useful default implementation of a YAML parser. Unfortunately it seems the current version of `yaml2yeast` does not work as expected.

# Steps to Reproduce the Problem

1. Install YamlReference

   ```sh
   cabal update
   cabal install yamlreference
   ```

2. Run `yaml2yeast`

   ```sh
   echo '- Hi YAML' | yaml2yeast
   ```

# Expected Result

The last command should print something like this:

```
# B: 0, C: 0, L: 1, c: 0
O
# B: 0, C: 0, L: 1, c: 0
N
# B: 0, C: 0, L: 1, c: 0
Q
# B: 0, C: 0, L: 1, c: 0
I-
# B: 1, C: 1, L: 1, c: 1
w
# B: 2, C: 2, L: 1, c: 2
N
# B: 2, C: 2, L: 1, c: 2
S
# B: 2, C: 2, L: 1, c: 2
THi YAML
# B: 9, C: 9, L: 1, c: 9
s
# B: 9, C: 9, L: 1, c: 9
n
# B: 9, C: 9, L: 1, c: 9
b\x0a
# B: 10, C: 10, L: 2, c: 0
q
# B: 10, C: 10, L: 2, c: 0
n
# B: 10, C: 10, L: 2, c: 0
o
```

# Actual Result

The command exits with the error code 1 printing the following message:

```
yaml2yeast: No production l-yaml-stream or it doesn't take this combination of parameters
CallStack (from HasCallStack):
  error, called at yaml2yeast/Main.hs:277:26 in main:Main
```

.

# System Information

- OS: macOS 10.13.3
- GHC: The Glorious Glasgow Haskell Compilation System, version 8.2.2

**Comment by orenbenkiki** [comment]
Thanks for the bug & the fix.

**Comment by sanssecours** [comment]
Wow, that was fast 😃. Thanks for merging the changes.
