### ISSUE TITLE
invalid bom input actually valid

### ISSUE THREAD

**Issue by omry** [orenbenkiki/yamlreference#7]
Hi Oren,
Why is this considered invalid?

https://github.com/orenbenkiki/yamlreference/blob/bf471f804ccd014fcdded3a8c74c338df8f33c85/tests/c-byte-order-mark.invalid.input#L1

IT does lack a bom, per the [yaml 1.2 specification](https://yaml.org/spec/1.2/spec.html#id2771184)s by default utf-8 should be assumed in such a case.

**Comment by orenbenkiki** [comment]
Yes, utf-8 would be assumed in that case. However the test isn't for "how should this input be parsed" but rather "what should this parsing production do if it sees the following characters". In general, the production tests work on fragments of the input rather than a complete input.

**Comment by omry** [comment]
by parsing production do you mean the lexer/tokenizer?
I have seen in other files that identical inputs results in different detected tokens in the output - do you apply specific fragments to specific files or do you run them through the lexer?

(Sorry for not reading the code, I don't know a bit of Haskell).

**Comment by orenbenkiki** [comment]
Yes, the tests apply a specific parsing production (as per the spec) to specific input (fragments) and examine the results. This allows for testing all sort of edge cases without a lot of boilerplate. It follows that one may have two different test files with the same contents and different expected results (as different parsing productions are applied to the same data).
